/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp io.github.ssk.TaskManager.xml -a taskmanager_adapter
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "taskmanager_adapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TaskManagerAdaptor
 */

TaskManagerAdaptor::TaskManagerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TaskManagerAdaptor::~TaskManagerAdaptor()
{
    // destructor
}

void TaskManagerAdaptor::dispatchTask(int type, int id, const QString &name, const QString &command)
{
    // handle method call io.github.ssk.TaskManager.dispatchTask
    QMetaObject::invokeMethod(parent(), "dispatchTask", Q_ARG(int, type), Q_ARG(int, id), Q_ARG(QString, name), Q_ARG(QString, command));
}

